class CompaniesController < ApplicationController

		def index
			 @companies = Company.all

		    respond_to do |format|
		      format.html
		      format.json { render :json => @companies }
	    	end

		 end


		  #lets us add more users
		  def create

		  	#puts "WE GOT TO CREATE"

		    @company = Company.new

		    #Another way of doing this in a single line is to do it:
		    #@company = Company.new(params[:company])

		    #Need the [:teams] because its a hash based on the post, and then
		    #within that hash, we access the [:name]
		    @company.company_name = params[:company][:company_name]

		    @company.save!

#companies_url is autogenerated by rails from the "resources: companies" that we typed
		    respond_to do |format|
		      format.html { redirect_to companies_url }
		      format.json { render :json => @company }
		    end

		  end

		 #update our teams us add more teams
		  def update
		  	@company = Company.find(params[:id])
		  	@company.company_name = params[:company][:company_name]
		    
		    respond_to do |format|
		      format.html { redirect_to companies_url }
		      format.json { render :json => @company }
		    end

		  end

		 #gives us information about one of the teams
		 def show

		 	@company = Company.find(params[:id])

		    respond_to do |format|
		      format.html
		      format.json { render :json => @company}
		    end

		 end
			
		 #Destroys a team
		 def destroy
		 	@company = Company.find(params[:id])
		 	@company.delete

		 	respond_to do |format|
		  	  format.html { redirect_to companies_url }
		      format.json { head :ok }
		 	 end

		 end

		 #Returns all of the good students in a JSON hash
		 # def fivehundred_teams
		  #  @teams = Team.fivehundred_teams

		   # respond_to do |format|
		    #  format.json { render :json => @teams }
		    #end
		  
		  #end



end
